import React from "react";
import Goal1 from "../../assets/images/goals.png";
import Goal2 from "../../assets/images/goal2.png";
import Goal3 from "../../assets/images/goal3.png";

const Three = () => {
  return (
    <section className="py-20">
      <div className="grid lg:grid-cols-2 gap-20">
        <div className="space-y-5">
          <h1 className="text-5xl font-bold text-blue-500">The Problem </h1>
          <p>
            One very obvious reason why the uptake of electric cars vary between
            countries and is pretty slow in most countries is Cost. From
            research made, the high cost of purchasing one is the major reason
            for hesitancy in Nigeria.
          </p>
        </div>
        <div className="space-y-5">
          <h1 className="text-5xl font-bold text-blue-500"> The Goal </h1>
          <p>
            The goal of this project is simply to give individuals who are
            willing, the chance to own an Electric car on loan, allow the car to
            go on rides using the in-house hailing service, while the owner
            monitors the car using the app. Hence the car loans can be paid back
            automatically with the revenue generated by the car. On the other
            hand, users can also book rides with these self piloted vehicles
            using the app as well.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-3 items-end py-20">
        <img src={Goal2} alt="" />
        <img src={Goal1} alt="" />
        <img src={Goal3} alt="" />
      </div>
    </section>
  );
};

export default Three;
